// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABBwFgA39/fwACDwEDZW52Bm1lbW9yeQIAEAMDAgAABgkBfwFBgIDAAAsHIwIOcmVjaXByb2NhbF9mNjQAAA5yZWNpcHJvY2FsX2YzMgABCokIAoYEAwV/AXsBfwJAAkAgAkF+cSIDDQBBACEEDAELAkACQCADQX9qIgVBAUcNAEEAIQQMAQsgBUEBdkEBakF+cSIGQQF0IQQgASEDIAAhBwNAIAP9DAAAAAAAAPA/AAAAAAAA8D8iCCAH/QADAP3zAf0LAwAgA0EQaiAIIAdBEGr9AAMA/fMB/QsDACADQSBqIQMgB0EgaiEHIAZBfmoiBg0ACwsgBUECcQ0AIAEgBEEDdCIDav0MAAAAAAAA8D8AAAAAAADwPyAAIANq/QADAP3zAf0LAwAgBEECaiEECwJAIAIgBE0NAAJAIAIgBGsiBUEESQ0AIAEgAGtBEEkNACAAIARBA3QiB2ohAyABIAdqIQcgBCAFQX5xIglqIQQgCSEGA0AgB/0MAAAAAAAA8D8AAAAAAADwPyAD/QADAP3zAf0LAwAgA0EQaiEDIAdBEGohByAGQX5qIgYNAAsgBSAJRg0BCyAEQQFqIQMCQCACIARrQQFxRQ0AIAEgBEEDdCIHakQAAAAAAADwPyAAIAdqKwMAozkDACADIQQLIAIgA0YNACACIARrIQYgASAEQQN0IgdqIQMgACAHaiEHA0AgA0QAAAAAAADwPyAHKwMAozkDACADQQhqRAAAAAAAAPA/IAdBCGorAwCjOQMAIANBEGohAyAHQRBqIQcgBkF+aiIGDQALCwv+AwMFfwF7AX8CQAJAIAJBfHEiAw0AQQAhBAwBCwJAAkAgA0F/aiIFQQNHDQBBACEEDAELIAVBAnZBAWpB/v///wdxIgZBAnQhBCABIQMgACEHA0AgA/0MAACAPwAAgD8AAIA/AACAPyIIIAf9AAIA/ecB/QsCACADQRBqIAggB0EQav0AAgD95wH9CwIAIANBIGohAyAHQSBqIQcgBkF+aiIGDQALCyAFQQRxDQAgASAEQQJ0IgNq/QwAAIA/AACAPwAAgD8AAIA/IAAgA2r9AAIA/ecB/QsCACAEQQRqIQQLAkAgAiAETQ0AAkAgAiAEayIFQQRJDQAgASAAa0EQSQ0AIAAgBEECdCIHaiEDIAEgB2ohByAEIAVBfHEiCWohBCAJIQYDQCAH/QwAAIA/AACAPwAAgD8AAIA/IAP9AAIA/ecB/QsCACADQRBqIQMgB0EQaiEHIAZBfGoiBg0ACyAFIAlGDQELIARBAWohAwJAIAIgBGtBAXFFDQAgASAEQQJ0IgdqQwAAgD8gACAHaioCAJU4AgAgAyEECyACIANGDQAgAiAEayEGIAEgBEECdCIHaiEDIAAgB2ohBwNAIANDAACAPyAHKgIAlTgCACADQQRqQwAAgD8gB0EEaioCAJU4AgAgA0EIaiEDIAdBCGohByAGQX5qIgYNAAsLCw==';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function reciprocal_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['reciprocal_f64'] as (...args: number[]) => void)(a, out, N);
}

export function reciprocal_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['reciprocal_f32'] as (...args: number[]) => void)(a, out, N);
}
